// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/study.proto

package study

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 账号数据
type AccountData struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Passwd               string   `protobuf:"bytes,3,opt,name=passwd,proto3" json:"passwd,omitempty"`
	EquipmentId          string   `protobuf:"bytes,4,opt,name=equipmentId,proto3" json:"equipmentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountData) Reset()         { *m = AccountData{} }
func (m *AccountData) String() string { return proto.CompactTextString(m) }
func (*AccountData) ProtoMessage()    {}
func (*AccountData) Descriptor() ([]byte, []int) {
	return fileDescriptor_09cc869e7b177063, []int{0}
}

func (m *AccountData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountData.Unmarshal(m, b)
}
func (m *AccountData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountData.Marshal(b, m, deterministic)
}
func (m *AccountData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountData.Merge(m, src)
}
func (m *AccountData) XXX_Size() int {
	return xxx_messageInfo_AccountData.Size(m)
}
func (m *AccountData) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountData.DiscardUnknown(m)
}

var xxx_messageInfo_AccountData proto.InternalMessageInfo

func (m *AccountData) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AccountData) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *AccountData) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *AccountData) GetEquipmentId() string {
	if m != nil {
		return m.EquipmentId
	}
	return ""
}

// 用户基础数据
type BaseData struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarURL            string   `protobuf:"bytes,3,opt,name=avatarURL,proto3" json:"avatarURL,omitempty"`
	Score                uint64   `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	IsOnline             bool     `protobuf:"varint,6,opt,name=isOnline,proto3" json:"isOnline,omitempty"`
	OfflineTime          int64    `protobuf:"varint,7,opt,name=offlineTime,proto3" json:"offlineTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseData) Reset()         { *m = BaseData{} }
func (m *BaseData) String() string { return proto.CompactTextString(m) }
func (*BaseData) ProtoMessage()    {}
func (*BaseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_09cc869e7b177063, []int{1}
}

func (m *BaseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseData.Unmarshal(m, b)
}
func (m *BaseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseData.Marshal(b, m, deterministic)
}
func (m *BaseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseData.Merge(m, src)
}
func (m *BaseData) XXX_Size() int {
	return xxx_messageInfo_BaseData.Size(m)
}
func (m *BaseData) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseData.DiscardUnknown(m)
}

var xxx_messageInfo_BaseData proto.InternalMessageInfo

func (m *BaseData) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *BaseData) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *BaseData) GetAvatarURL() string {
	if m != nil {
		return m.AvatarURL
	}
	return ""
}

func (m *BaseData) GetScore() uint64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *BaseData) GetIsOnline() bool {
	if m != nil {
		return m.IsOnline
	}
	return false
}

func (m *BaseData) GetOfflineTime() int64 {
	if m != nil {
		return m.OfflineTime
	}
	return 0
}

// 用户的游戏数据 （还有其他数据，数据比较大）
type GameData struct {
	LevelData            *LevelData        `protobuf:"bytes,1,opt,name=levelData,proto3" json:"levelData,omitempty"`
	ShopData             map[uint32]uint32 `protobuf:"bytes,2,rep,name=shopData,proto3" json:"shopData,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Statistics           *StatisticsData   `protobuf:"bytes,3,opt,name=statistics,proto3" json:"statistics,omitempty"`
	Setting              *GameSetting      `protobuf:"bytes,4,opt,name=setting,proto3" json:"setting,omitempty"`
	Material             *MaterialData     `protobuf:"bytes,5,opt,name=material,proto3" json:"material,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GameData) Reset()         { *m = GameData{} }
func (m *GameData) String() string { return proto.CompactTextString(m) }
func (*GameData) ProtoMessage()    {}
func (*GameData) Descriptor() ([]byte, []int) {
	return fileDescriptor_09cc869e7b177063, []int{2}
}

func (m *GameData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameData.Unmarshal(m, b)
}
func (m *GameData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameData.Marshal(b, m, deterministic)
}
func (m *GameData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameData.Merge(m, src)
}
func (m *GameData) XXX_Size() int {
	return xxx_messageInfo_GameData.Size(m)
}
func (m *GameData) XXX_DiscardUnknown() {
	xxx_messageInfo_GameData.DiscardUnknown(m)
}

var xxx_messageInfo_GameData proto.InternalMessageInfo

func (m *GameData) GetLevelData() *LevelData {
	if m != nil {
		return m.LevelData
	}
	return nil
}

func (m *GameData) GetShopData() map[uint32]uint32 {
	if m != nil {
		return m.ShopData
	}
	return nil
}

func (m *GameData) GetStatistics() *StatisticsData {
	if m != nil {
		return m.Statistics
	}
	return nil
}

func (m *GameData) GetSetting() *GameSetting {
	if m != nil {
		return m.Setting
	}
	return nil
}

func (m *GameData) GetMaterial() *MaterialData {
	if m != nil {
		return m.Material
	}
	return nil
}

// 关卡数据
type LevelData struct {
	CurLevel             uint32   `protobuf:"varint,1,opt,name=curLevel,proto3" json:"curLevel,omitempty"`
	FinishTask           []uint32 `protobuf:"varint,2,rep,packed,name=finishTask,proto3" json:"finishTask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LevelData) Reset()         { *m = LevelData{} }
func (m *LevelData) String() string { return proto.CompactTextString(m) }
func (*LevelData) ProtoMessage()    {}
func (*LevelData) Descriptor() ([]byte, []int) {
	return fileDescriptor_09cc869e7b177063, []int{3}
}

func (m *LevelData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LevelData.Unmarshal(m, b)
}
func (m *LevelData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LevelData.Marshal(b, m, deterministic)
}
func (m *LevelData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LevelData.Merge(m, src)
}
func (m *LevelData) XXX_Size() int {
	return xxx_messageInfo_LevelData.Size(m)
}
func (m *LevelData) XXX_DiscardUnknown() {
	xxx_messageInfo_LevelData.DiscardUnknown(m)
}

var xxx_messageInfo_LevelData proto.InternalMessageInfo

func (m *LevelData) GetCurLevel() uint32 {
	if m != nil {
		return m.CurLevel
	}
	return 0
}

func (m *LevelData) GetFinishTask() []uint32 {
	if m != nil {
		return m.FinishTask
	}
	return nil
}

// 统计类类数据
type StatisticsData struct {
	TotalOnlineTime      int64    `protobuf:"varint,1,opt,name=totalOnlineTime,proto3" json:"totalOnlineTime,omitempty"`
	TotalUseMoney        uint32   `protobuf:"varint,2,opt,name=totalUseMoney,proto3" json:"totalUseMoney,omitempty"`
	TotalUseStar         uint32   `protobuf:"varint,3,opt,name=totalUseStar,proto3" json:"totalUseStar,omitempty"`
	TotalExposureHeat    uint32   `protobuf:"varint,4,opt,name=totalExposureHeat,proto3" json:"totalExposureHeat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatisticsData) Reset()         { *m = StatisticsData{} }
func (m *StatisticsData) String() string { return proto.CompactTextString(m) }
func (*StatisticsData) ProtoMessage()    {}
func (*StatisticsData) Descriptor() ([]byte, []int) {
	return fileDescriptor_09cc869e7b177063, []int{4}
}

func (m *StatisticsData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatisticsData.Unmarshal(m, b)
}
func (m *StatisticsData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatisticsData.Marshal(b, m, deterministic)
}
func (m *StatisticsData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatisticsData.Merge(m, src)
}
func (m *StatisticsData) XXX_Size() int {
	return xxx_messageInfo_StatisticsData.Size(m)
}
func (m *StatisticsData) XXX_DiscardUnknown() {
	xxx_messageInfo_StatisticsData.DiscardUnknown(m)
}

var xxx_messageInfo_StatisticsData proto.InternalMessageInfo

func (m *StatisticsData) GetTotalOnlineTime() int64 {
	if m != nil {
		return m.TotalOnlineTime
	}
	return 0
}

func (m *StatisticsData) GetTotalUseMoney() uint32 {
	if m != nil {
		return m.TotalUseMoney
	}
	return 0
}

func (m *StatisticsData) GetTotalUseStar() uint32 {
	if m != nil {
		return m.TotalUseStar
	}
	return 0
}

func (m *StatisticsData) GetTotalExposureHeat() uint32 {
	if m != nil {
		return m.TotalExposureHeat
	}
	return 0
}

// 游戏配置
type GameSetting struct {
	Switch               uint32   `protobuf:"varint,1,opt,name=switch,proto3" json:"switch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameSetting) Reset()         { *m = GameSetting{} }
func (m *GameSetting) String() string { return proto.CompactTextString(m) }
func (*GameSetting) ProtoMessage()    {}
func (*GameSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_09cc869e7b177063, []int{5}
}

func (m *GameSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameSetting.Unmarshal(m, b)
}
func (m *GameSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameSetting.Marshal(b, m, deterministic)
}
func (m *GameSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameSetting.Merge(m, src)
}
func (m *GameSetting) XXX_Size() int {
	return xxx_messageInfo_GameSetting.Size(m)
}
func (m *GameSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_GameSetting.DiscardUnknown(m)
}

var xxx_messageInfo_GameSetting proto.InternalMessageInfo

func (m *GameSetting) GetSwitch() uint32 {
	if m != nil {
		return m.Switch
	}
	return 0
}

type MaterialData struct {
	Money                int32             `protobuf:"varint,1,opt,name=money,proto3" json:"money,omitempty"`
	Star                 uint32            `protobuf:"varint,2,opt,name=star,proto3" json:"star,omitempty"`
	Warehouse            map[uint32]uint32 `protobuf:"bytes,3,rep,name=warehouse,proto3" json:"warehouse,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	ExposureMoney        uint32            `protobuf:"varint,4,opt,name=exposureMoney,proto3" json:"exposureMoney,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MaterialData) Reset()         { *m = MaterialData{} }
func (m *MaterialData) String() string { return proto.CompactTextString(m) }
func (*MaterialData) ProtoMessage()    {}
func (*MaterialData) Descriptor() ([]byte, []int) {
	return fileDescriptor_09cc869e7b177063, []int{6}
}

func (m *MaterialData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaterialData.Unmarshal(m, b)
}
func (m *MaterialData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaterialData.Marshal(b, m, deterministic)
}
func (m *MaterialData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaterialData.Merge(m, src)
}
func (m *MaterialData) XXX_Size() int {
	return xxx_messageInfo_MaterialData.Size(m)
}
func (m *MaterialData) XXX_DiscardUnknown() {
	xxx_messageInfo_MaterialData.DiscardUnknown(m)
}

var xxx_messageInfo_MaterialData proto.InternalMessageInfo

func (m *MaterialData) GetMoney() int32 {
	if m != nil {
		return m.Money
	}
	return 0
}

func (m *MaterialData) GetStar() uint32 {
	if m != nil {
		return m.Star
	}
	return 0
}

func (m *MaterialData) GetWarehouse() map[uint32]uint32 {
	if m != nil {
		return m.Warehouse
	}
	return nil
}

func (m *MaterialData) GetExposureMoney() uint32 {
	if m != nil {
		return m.ExposureMoney
	}
	return 0
}

func init() {
	proto.RegisterType((*AccountData)(nil), "study.AccountData")
	proto.RegisterType((*BaseData)(nil), "study.BaseData")
	proto.RegisterType((*GameData)(nil), "study.GameData")
	proto.RegisterMapType((map[uint32]uint32)(nil), "study.GameData.ShopDataEntry")
	proto.RegisterType((*LevelData)(nil), "study.LevelData")
	proto.RegisterType((*StatisticsData)(nil), "study.StatisticsData")
	proto.RegisterType((*GameSetting)(nil), "study.GameSetting")
	proto.RegisterType((*MaterialData)(nil), "study.MaterialData")
	proto.RegisterMapType((map[uint32]uint32)(nil), "study.MaterialData.WarehouseEntry")
}

func init() { proto.RegisterFile("proto/study.proto", fileDescriptor_09cc869e7b177063) }

var fileDescriptor_09cc869e7b177063 = []byte{
	// 589 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xed, 0x6a, 0xd4, 0x40,
	0x14, 0x25, 0xbb, 0xdd, 0x6e, 0xf6, 0xa6, 0xe9, 0xc7, 0xf8, 0x41, 0x28, 0x2a, 0x21, 0x28, 0xe4,
	0x47, 0x49, 0x61, 0x45, 0x50, 0xeb, 0x0f, 0x2d, 0x96, 0x5a, 0x68, 0x11, 0x66, 0x5b, 0x04, 0xff,
	0x8d, 0xd9, 0xa9, 0x3b, 0x34, 0x1f, 0x6b, 0x66, 0xd2, 0xba, 0x6f, 0x25, 0x3e, 0x85, 0x4f, 0xe1,
	0xb3, 0xc8, 0xdc, 0x99, 0xa4, 0x89, 0x8a, 0xe0, 0xbf, 0x39, 0xe7, 0x9e, 0x99, 0x7b, 0xe6, 0xdc,
	0x49, 0x60, 0x67, 0x59, 0x95, 0xaa, 0xdc, 0x97, 0xaa, 0x9e, 0xaf, 0x12, 0x5c, 0x93, 0x11, 0x82,
	0x68, 0x05, 0xde, 0x9b, 0x34, 0x2d, 0xeb, 0x42, 0xbd, 0x65, 0x8a, 0x91, 0xfb, 0xb0, 0x5e, 0x4b,
	0x5e, 0x9d, 0xcc, 0x03, 0x27, 0x74, 0xe2, 0x11, 0xb5, 0x88, 0x04, 0x30, 0x66, 0x46, 0x16, 0x0c,
	0x42, 0x27, 0x9e, 0xd0, 0x06, 0xea, 0x1d, 0x4b, 0x26, 0xe5, 0xcd, 0x3c, 0x18, 0x62, 0xc1, 0x22,
	0x12, 0x82, 0xc7, 0xbf, 0xd4, 0x62, 0x99, 0xf3, 0x42, 0x9d, 0xcc, 0x83, 0x35, 0x2c, 0x76, 0xa9,
	0xe8, 0x9b, 0x03, 0xee, 0x21, 0x93, 0xfc, 0x9f, 0x8d, 0x77, 0xc1, 0x2d, 0x44, 0x7a, 0x55, 0xb0,
	0x9c, 0xdb, 0xce, 0x2d, 0x26, 0x0f, 0x60, 0xc2, 0xae, 0x99, 0x62, 0xd5, 0x05, 0x3d, 0xb5, 0xdd,
	0x6f, 0x09, 0x72, 0x17, 0x46, 0x32, 0x2d, 0x2b, 0x8e, 0xad, 0xd7, 0xa8, 0x01, 0xfa, 0x3c, 0x21,
	0xdf, 0x17, 0x99, 0x28, 0x78, 0xb0, 0x1e, 0x3a, 0xb1, 0x4b, 0x5b, 0xac, 0x2d, 0x97, 0x97, 0x97,
	0x7a, 0x79, 0x2e, 0x72, 0x1e, 0x8c, 0x43, 0x27, 0x1e, 0xd2, 0x2e, 0x15, 0xfd, 0x18, 0x80, 0x7b,
	0xcc, 0x72, 0x63, 0x39, 0x81, 0x49, 0xc6, 0xaf, 0x79, 0xa6, 0x01, 0xba, 0xf6, 0xa6, 0xdb, 0x89,
	0x89, 0xf8, 0xb4, 0xe1, 0xe9, 0xad, 0x84, 0xbc, 0x00, 0x57, 0x2e, 0xca, 0x25, 0xca, 0x07, 0xe1,
	0x30, 0xf6, 0xa6, 0x0f, 0xad, 0xbc, 0x39, 0x32, 0x99, 0xd9, 0xfa, 0x51, 0xa1, 0xaa, 0x15, 0x6d,
	0xe5, 0xe4, 0x19, 0x80, 0x54, 0x4c, 0x09, 0xa9, 0x44, 0x2a, 0xf1, 0xaa, 0xde, 0xf4, 0x9e, 0xdd,
	0x3c, 0x6b, 0x0b, 0xd8, 0xb0, 0x23, 0x24, 0x7b, 0x30, 0x96, 0x5c, 0x29, 0x51, 0x7c, 0xc6, 0x10,
	0xbc, 0x29, 0xe9, 0x34, 0x9c, 0x99, 0x0a, 0x6d, 0x24, 0x64, 0x1f, 0xdc, 0x9c, 0x29, 0x5e, 0x09,
	0x96, 0x05, 0x23, 0x94, 0xdf, 0xb1, 0xf2, 0x33, 0x4b, 0x63, 0x83, 0x56, 0xb4, 0x7b, 0x00, 0x7e,
	0xcf, 0x30, 0xd9, 0x86, 0xe1, 0x15, 0x5f, 0x61, 0x16, 0x3e, 0xd5, 0x4b, 0x3d, 0x84, 0x6b, 0x96,
	0xd5, 0x66, 0x76, 0x3e, 0x35, 0xe0, 0xe5, 0xe0, 0xb9, 0x13, 0x1d, 0xc3, 0xa4, 0x4d, 0x49, 0x4f,
	0x25, 0xad, 0x2b, 0xc4, 0x76, 0x77, 0x8b, 0xc9, 0x23, 0x80, 0x4b, 0x51, 0x08, 0xb9, 0x38, 0x67,
	0xf2, 0x0a, 0x83, 0xf3, 0x69, 0x87, 0x89, 0xbe, 0x3b, 0xb0, 0xd9, 0xcf, 0x80, 0xc4, 0xb0, 0xa5,
	0x4a, 0xc5, 0x32, 0x33, 0x57, 0x1c, 0xa6, 0x83, 0xc3, 0xfc, 0x9d, 0x26, 0x8f, 0xc1, 0x47, 0xea,
	0x42, 0xf2, 0xb3, 0xb2, 0xe0, 0x2b, 0xeb, 0xb3, 0x4f, 0x92, 0x08, 0x36, 0x1a, 0x62, 0xa6, 0x58,
	0x85, 0x03, 0xf0, 0x69, 0x8f, 0x23, 0x7b, 0xb0, 0x83, 0xf8, 0xe8, 0xeb, 0xb2, 0x94, 0x75, 0xc5,
	0xdf, 0x71, 0xa6, 0x30, 0x75, 0x9f, 0xfe, 0x59, 0x88, 0x9e, 0x80, 0xd7, 0x99, 0x81, 0x7e, 0xfd,
	0xf2, 0x46, 0xa8, 0x74, 0x61, 0x6f, 0x6f, 0x51, 0xf4, 0xd3, 0x81, 0x8d, 0x6e, 0xf8, 0x3a, 0xcf,
	0x1c, 0x7d, 0x9a, 0xaf, 0xc4, 0x00, 0x42, 0x60, 0x4d, 0x6a, 0x5f, 0xc6, 0x3c, 0xae, 0xc9, 0x6b,
	0x98, 0xdc, 0xb0, 0x8a, 0x2f, 0xca, 0x5a, 0xf2, 0x60, 0x88, 0xcf, 0x2d, 0xfa, 0xcb, 0x38, 0x93,
	0x0f, 0x8d, 0xc8, 0xbc, 0xb9, 0xdb, 0x4d, 0x3a, 0x1b, 0x6e, 0x3d, 0x9b, 0x6c, 0xcc, 0x6d, 0xfa,
	0xe4, 0xee, 0x2b, 0xd8, 0xec, 0x1f, 0xf1, 0x3f, 0xaf, 0x60, 0x3a, 0x86, 0xd1, 0xec, 0x9c, 0x4b,
	0x75, 0xb8, 0xf5, 0xd1, 0x4f, 0xf6, 0xf1, 0xcf, 0x74, 0x80, 0x26, 0x3f, 0xad, 0x23, 0x78, 0xfa,
	0x2b, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x91, 0x11, 0xda, 0xbb, 0x04, 0x00, 0x00,
}
