// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/study.proto

package study

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for STest service

func NewSTestEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for STest service

type STestService interface {
}

type sTestService struct {
	c    client.Client
	name string
}

func NewSTestService(name string, c client.Client) STestService {
	return &sTestService{
		c:    c,
		name: name,
	}
}

// Server API for STest service

type STestHandler interface {
}

func RegisterSTestHandler(s server.Server, hdlr STestHandler, opts ...server.HandlerOption) error {
	type sTest interface {
	}
	type STest struct {
		sTest
	}
	h := &sTestHandler{hdlr}
	return s.Handle(s.NewHandler(&STest{h}, opts...))
}

type sTestHandler struct {
	STestHandler
}
